### ISSUE TITLE
Lack of content

### ISSUE THREAD

**Issue by FredrikAugust** [blauks/blauks#1]
I wanted some content, but there is none? Smh

**Comment by kharann** [comment]
Hello! I wonder if this issue has been solved yet ? I'm using this repo in one of my projects and stumbled upon the very same issue. Therefor i shall bump this thread in hope that the maintainer will answer my cries for help.

**Comment by blauks** [comment]
Sorry for the lack of responses from my team. I have just hired new staff, and they starting on their training period right now so we have not been able to answer to all of our issues. I will be sure to push my project files as soon as possible, so that you can start using our code in your projects! Remember if there are any more problems do not be afraid to ask, we are here to help. Or if you see something you think you could fix, just send a pull request and we will take a look. Go open source!

Best wishes from us at Brooks Consulting AS!

**Comment by blauks** [comment]
We have now fixed the issue, and will close this thread. Thanks for contacting Brooks Consulting AS, and we hope you have a nice day!
